services:
  app:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: mysql:8.0
    container_name: hyuswim-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=128M
      --innodb-log-buffer-size=16M
      --max-connections=50
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u$DB_USER -p$DB_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:

