spring:
  jpa:
    hibernate:
      ddl-auto: update   # 운영은 validate 권장
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
