name: Lint Workflows

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow syntax
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const yaml = require("js-yaml");
            const files = fs.readdirSync(".github/workflows");
            for (const file of files) {
              if (file.endsWith(".yml") || file.endsWith(".yaml")) {
                try {
                  yaml.load(fs.readFileSync(`.github/workflows/${file}`, "utf8"));
                  core.info(`✅ ${file} is valid`);
                } catch (e) {
                  core.setFailed(`❌ ${file} has invalid YAML: ${e.message}`);
                }
              }
            }
